### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Gdy-myproject** [wujiekd/wujiekd-WeChat-Big-Data-Challenge-2022-National-Second-Prize#1]
博主您好，我想获取微信大数据竞赛初赛的数据，您方便嘛？

**Comment by wujiekd** [comment]
数据官方不让泄露噢

**Comment by Gdy-myproject** [comment]
初赛的数据不是开放的吗学长？



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 25, 2022 10:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wujiekd/WeChat-Big-Data-Challenge-2022-National-Second-Prize] Request (Issue #1)

**Comment by wujiekd** [comment]
只开放给报名选手了

**Comment by Gdy-myproject** [comment]
好趴 还是谢谢你呀学长



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 25, 2022 10:46 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wujiekd/WeChat-Big-Data-Challenge-2022-National-Second-Prize]Request (Issue #1)
